title: BoringSec
description: Giovanni Cattani's Blog

info:
   author: 		"Giovanni Cattani"
   email: 		"giov.catt@gmail.com"
   domain: 		"gcattani.co.vu"
   analytics:		"UA-39540268-1"

markdown:		redcarpet
permalink: 		/:year/:month/:title
highlighter: 		pygments
exclude: 		[README.md, LICENSE, Makefile]
